#!/usr/bin/env bash

ln -sf /homeassistant/predbat_ha/custom_components/predbat_ha /config/custom_components/
ln -sf /homeassistant/batpred/apps/predbat/predbat.py /config/custom_components/predbat_ha/predbat.py
